# Zmqpp

language: cpp

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update

install:
 # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  # Requirements
  - sudo apt-get install libboost-all-dev

before_script:
  # Perform regression test build against ZeroMQ v4.x
  - git clone git://github.com/zeromq/zeromq4-x.git
  - cd zeromq4-x
  - ./autogen.sh
  - ./configure && make -j4
  - sudo make install
  - sudo ldconfig
  - cd ..

script:
  - make CXXFLAGS='-DTRAVIS_CI_BUILD' check
